import { NextRequest, NextResponse } from 'next/server';
import { Octokit } from '@octokit/rest';
import OpenAI from 'openai';

/**
 * Create Issue API - Actually creates a GitHub issue with AI recommendations
 * This is REAL - it will create an actual issue on the repository
 */

export async function POST(request: NextRequest) {
  try {
    const { repoUrl, analysis } = await request.json();

    if (!repoUrl) {
      return NextResponse.json(
        { error: 'Repository URL is required' },
        { status: 400 }
      );
    }

    // Parse GitHub URL
    const urlPattern = /github\.com\/([^\/]+)\/([^\/]+)/;
    const match = repoUrl.match(urlPattern);

    if (!match) {
      return NextResponse.json(
        { error: 'Invalid GitHub URL' },
        { status: 400 }
      );
    }

    const [, owner, repo] = match;
    const repoName = repo.replace('.git', '');

    // Check if we have required API keys
    if (!process.env.GITHUB_TOKEN) {
      return NextResponse.json({
        success: false,
        error: 'GitHub token not configured',
        message: 'Add GITHUB_TOKEN to .env.local to create real issues'
      }, { status: 400 });
    }

    // Initialize GitHub API
    const octokit = new Octokit({
      auth: process.env.GITHUB_TOKEN,
    });

    // Generate issue content with AI if available
    let issueBody = '';
    
    if (process.env.OPENAI_API_KEY && analysis) {
      const openai = new OpenAI({
        apiKey: process.env.OPENAI_API_KEY,
      });

      const prompt = `Create a detailed GitHub issue for repository modernization based on this analysis:

Repository: ${owner}/${repoName}
Issues Found: ${analysis.issues?.length || 0}
Framework: ${analysis.framework || 'Unknown'}
Dependencies: ${analysis.dependencies || 0}

Issues:
${analysis.issues?.map((issue: any) => `- ${issue.message}: ${issue.recommendation}`).join('\n') || 'None detected'}

Create a well-formatted GitHub issue with:
1. Brief summary of current state
2. Specific issues found (with severity)
3. Recommended actions (prioritized)
4. Estimated effort
5. Benefits of modernization

Use GitHub markdown formatting. Be professional and actionable.`;

      try {
        const completion = await openai.chat.completions.create({
          model: 'gpt-4',
          messages: [
            {
              role: 'system',
              content: 'You are a senior software architect creating actionable GitHub issues for repository modernization. Use clear markdown formatting.',
            },
            {
              role: 'user',
              content: prompt,
            },
          ],
          max_tokens: 1000,
          temperature: 0.7,
        });

        issueBody = completion.choices[0].message.content || '';
      } catch (e) {
        console.error('OpenAI error:', e);
        // Fallback to manual issue body
      }
    }

    // Fallback issue body if AI not available
    if (!issueBody) {
      issueBody = `## 🔍 Repository Analysis

Ghost Commit has analyzed this repository and found opportunities for modernization.

### Current State
- **Framework**: ${analysis?.framework || 'Unknown'}
- **Dependencies**: ${analysis?.dependencies || 0}
- **Issues Found**: ${analysis?.issues?.length || 0}

### Issues Detected

${analysis?.issues?.map((issue: any, idx: number) => `
${idx + 1}. **${issue.message}** (${issue.severity})
   - ${issue.recommendation}
`).join('\n') || 'No major issues detected.'}

### Recommendations

${analysis?.recommendations?.topActions?.map((action: string, idx: number) => `
${idx + 1}. ${action}
`).join('\n') || 'Repository appears to be in good shape!'}

### Estimated Effort
${analysis?.recommendations?.estimatedTime || 'To be determined'}

---

*This issue was automatically generated by [Ghost Commit](https://github.com/yourusername/ghost-commit) - AI-powered repository resurrection.*
`;
    }

    // Create the actual GitHub issue
    const issue = await octokit.issues.create({
      owner,
      repo: repoName,
      title: '🔄 Repository Modernization Recommendations',
      body: issueBody,
      labels: ['enhancement', 'modernization'],
    });

    return NextResponse.json({
      success: true,
      issue: {
        number: issue.data.number,
        url: issue.data.html_url,
        title: issue.data.title,
        body: issue.data.body,
      },
      message: 'Issue created successfully!',
    });

  } catch (error: any) {
    console.error('Create issue error:', error);
    
    // Handle specific GitHub errors
    if (error.status === 404) {
      return NextResponse.json(
        { 
          success: false,
          error: 'Repository not found or no access',
          details: 'Make sure the repository exists and your GitHub token has access to it.',
        },
        { status: 404 }
      );
    }

    if (error.status === 403) {
      return NextResponse.json(
        { 
          success: false,
          error: 'Permission denied',
          details: 'Your GitHub token does not have permission to create issues on this repository.',
        },
        { status: 403 }
      );
    }

    if (error.status === 410) {
      return NextResponse.json(
        { 
          success: false,
          error: 'Issues are disabled',
          details: 'This repository has issues disabled.',
        },
        { status: 410 }
      );
    }
    
    return NextResponse.json(
      { 
        success: false,
        error: error.message || 'Failed to create issue',
        details: error.toString(),
      },
      { status: 500 }
    );
  }
}
